name: appli_ap_sante
description: "A new Flutter project."

# Prevent publishing to pub.dev
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.30.0
  cloud_firestore: ^4.15.8
  printing: ^5.12.0

  share_plus: ^7.2.1

  permission_handler: ^10.2.0
  open_file: ^3.2.1
  pdf: ^3.8.1
  path_provider: ^2.0.15

  flutter_speed_dial: ^7.0.0
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.7.2
  flutter_svg: ^2.1.0
  fl_chart: ^0.71.0
  animated_expandable_fab: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/fonts/

  fonts:
    - family: inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
        - asset: assets/fonts/Inter-Italic-VariableFont_opsz,wght.ttf
          style: italic
