name: appli_ap_sante
description: "A new Flutter project."

# Prevent publishing to pub.dev
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.30.0
  cloud_firestore: ^4.15.8
  pdf: ^3.10.4
  printing: ^5.12.0
  path_provider: ^2.1.1
  share_plus: ^7.2.1
  provider: ^6.1.1
  openid_client: ^0.4.9
  webview_flutter: ^4.13.0
  flutter_appauth: ^6.0.2
  flutter_secure_storage: ^9.0.0
  firebase_auth: ^4.2.5



  flutter_speed_dial: ^7.0.0
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.7.2
  flutter_svg: ^2.1.0
  fl_chart: ^0.71.0
  animated_expandable_fab: any



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/fonts/

  fonts:
    - family: inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
        - asset: assets/fonts/Inter-Italic-VariableFont_opsz,wght.ttf
          style: italic


