// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTwukfhZP_yaafJ-6-JZ-WRJB_rl0gnFQ',
    appId: '1:191460969582:web:77b1e6b2f7c88af347ea7f',
    messagingSenderId: '191460969582',
    projectId: 'app-sante-5e588',
    authDomain: 'app-sante-5e588.firebaseapp.com',
    storageBucket: 'app-sante-5e588.firebasestorage.app',
    measurementId: 'G-8EDT4QESFX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnZV6vO1PrTHAU02DXjqJeVzSr7oX7RA8',
    appId: '1:191460969582:android:41f394b7899062c747ea7f',
    messagingSenderId: '191460969582',
    projectId: 'app-sante-5e588',
    storageBucket: 'app-sante-5e588.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBObHZW3NXDUFNGVUfuTTMLuSWraD_oIr0',
    appId: '1:191460969582:ios:1d7673aa4cf3fbb147ea7f',
    messagingSenderId: '191460969582',
    projectId: 'app-sante-5e588',
    storageBucket: 'app-sante-5e588.firebasestorage.app',
    iosBundleId: 'com.example.appliApSante',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBObHZW3NXDUFNGVUfuTTMLuSWraD_oIr0',
    appId: '1:191460969582:ios:1d7673aa4cf3fbb147ea7f',
    messagingSenderId: '191460969582',
    projectId: 'app-sante-5e588',
    storageBucket: 'app-sante-5e588.firebasestorage.app',
    iosBundleId: 'com.example.appliApSante',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTwukfhZP_yaafJ-6-JZ-WRJB_rl0gnFQ',
    appId: '1:191460969582:web:51237fc8ae4e693b47ea7f',
    messagingSenderId: '191460969582',
    projectId: 'app-sante-5e588',
    authDomain: 'app-sante-5e588.firebaseapp.com',
    storageBucket: 'app-sante-5e588.firebasestorage.app',
    measurementId: 'G-ZPDJJ5KG8S',
  );
}
